### ISSUE TITLE
1.19.2 server crash in idle

### ISSUE THREAD

**Issue by ink717** [SuperMartijn642/MovingElevators#154] opened 2023-03-27 15:32 UTC
1.19.2 forge server

this suddenly happened not long ago and 3 nights in a row - server crash during the day when no one is online.

some didn't generate a crash log, but this is the one we had from the server so far.

The first one came in like this:
[crash-2023-03-26_09.24.40-server.txt](https://github.com/SuperMartijn642/MovingElevators/files/11080415/crash-2023-03-26_09.24.40-server.txt)

and then after 30 minutes, another crash log - and server eventually crashed.
[crash-2023-03-26_09.54.32-server.txt](https://github.com/SuperMartijn642/MovingElevators/files/11080403/crash-2023-03-26_09.54.32-server.txt)

**Comment by SuperMartijn642** [comment] 2023-03-27 16:26
That first log seems to be just running out of memory and could be caused by any of the mods you have installed or just Minecraft itself.

The second one seems to come from a remote elevator panel placed in an older version of Moving Elevators. It should update it's old data once it is loaded for 40 ticks. In your case it seems that the chunk the remote elevator panel is in got loaded, not ticked (or at least not 40 times) and then unloaded again.
No clue how that would happen without anyone online and seems you just got unlucky to encounter those specific circumstances.

I moved some things around to hopefully prevent the same from happening now in version 1.3.12 of Moving Elevators.
So should be fixed now, thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2023-03-27 16:26 UTC
Labels: crash

**Comment by ink717** [comment] 2023-03-27 16:42
thanks!
