### ISSUE TITLE
[Bug] Players falling through elevators.

### ISSUE THREAD

**Issue by cswimr** [SuperMartijn642/MovingElevators#117] opened 2022-04-09 23:26 UTC
**Version Info**
- Minecraft, 1.16.5
- Moving Elevators, 1.3.6

**Are you using OptiFine?**: Yes.

**Description of the Bug**
Sometimes, the player falls through the elevator, either while the elevator is moving or when the elevator stops. It happens far more often when the player has bad ping.

**Steps to Reproduce**
- Get on a server.
- Have bad ping (makes the bug more likely to occur).
- Use an elevator until you fall through it.

**Screenshots**
N/A

**Comment by SuperMartijn642** [comment] 2022-04-10 00:33
This is caused by OptiFine. OptiFine somehow changes player collision which causes players to fall through the elevator.
Sadly, not much I can do about it since OptiFine is closed source. I can't know what OptiFine changes and I don't want to waste my time randomly guessing.

**Comment by SuperMartijn642** [comment] 2022-04-10 00:34
Also, duplicate of #104

**Closed as completed by SuperMartijn642** 2022-04-10 00:34 UTC
Labels: bug, duplicate
