### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by AngleWyrm10** [SuperMartijn642/MovingElevators#139] opened 2022-08-09 12:58 UTC
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, 1.3.9

**Are you using OptiFine?**: Yes

**Steps to Reproduce**
Game fails to start
![Untitled](https://user-images.githubusercontent.com/55937426/183652455-013e0251-2b56-42bc-a080-abd663da15f2.png)

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/9290652/latest.log)

**Comment by SuperMartijn642** [comment] 2022-08-09 13:19
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method handleInteract(D)D in tombstone.mixins.json:ServerPacketMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.tombstone.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 29 more
```
The crash is caused by a mod with modid 'tombstone', seems to be unrelated to Moving Elevators.

**Comment by SuperMartijn642** [comment] 2022-08-11 14:32
Closing this as it's not related to Moving Elevators.

**Closed as completed by SuperMartijn642** 2022-08-11 14:32 UTC
Labels: crash
