### ISSUE TITLE
Elevator Got Slant and invisible with shaders [Bug] ...

### ISSUE THREAD

**Issue by Jerryw09** [SuperMartijn642/MovingElevators#146] opened 2022-11-23 00:13 UTC
**Version Info**
- Minecraft, 1.18.2-forge-40.0.24
- Moving Elevators, movingelevators-1.3.9-forge-mc1.18

**Are you using OptiFine?**:  Yes

**Description of the Bug**

It works fine before using optifine, when I install shaders, the elevator works but the elevator becomes invisible, and the texture of the elevator becomes slant and moves around.

**Steps to Reproduce**

Install Optifine
Put in shaders (mines are ComplementaryReimagined_r1.1.1)
Launch Minecraft
Build an elevator
works but becomes slant

**Screenshots**

https://mega.nz/file/JtAmSL4C#p6L7zzvRrXqTD4buObNyjBRA8mbWDFZrfFQi6TE_rZk

**Comment by Jerryw09** [comment] 2022-11-23 00:18
If that

**Comment by SuperMartijn642** [comment] 2022-11-23 01:59
Duplicate of #108. Blame OptiFine

**Closed as completed by SuperMartijn642** 2022-11-23 01:59 UTC
Labels: bug, duplicate, Caused by OptiFine
