### ISSUE TITLE
[Bug] Server Restart reset Elevator speed

### ISSUE THREAD

**Issue by Daihok41** [SuperMartijn642/MovingElevators#115] opened 2022-04-01 20:07 UTC
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, 1.3.5

**Are you using OptiFine?**: No

**Description of the Bug**
When restart Server it resets the elevators speed all the way back down. It also happens if players leave server it doesnt just happen with restart

**Steps to Reproduce**
Restart server or players leave server

**Screenshots**
...

**Comment by SuperMartijn642** [comment] 2022-04-03 16:04
Thank you for reporting the issue, it appears to be a duplicate of #102.

**Closed as completed by SuperMartijn642** 2022-04-03 16:04 UTC
Labels: bug, duplicate
