### ISSUE TITLE
[Crash] 1.12.2 Fatal Crash Due to Mod Confliction

### ISSUE THREAD

**Issue by MinicomSoftware** [SuperMartijn642/MovingElevators#57] opened 2021-05-02 20:18 UTC
**Version Info**
- Minecraft 1.12.2 
- Moving Elevators, v1.2.33-mc1.12

**Steps to Reproduce**
I run a public modded Minecraft Server, and this is how the user found this bug (which I replicated too)
Download the secretroomsmod-1.12.2-5.6.4.jar, and put any of their secret blocks on top of the Elevator Controller block from this mod. Crashes & player is unable to log back into that same chunk. The area crashes all players if near. I tried making a patch with my own independent mod, but I am unable to cancel the event in which a player places the secret rooms block on top of the elevator controller block. 

Here are some resource names that causes this:
secretroomsmod:ghost_block

movingelevators:elevator_block

**Crash report (~/logs/latest.log)**
https://paste.dimdev.org/atumikuped.mccrash
[crash-2021-05-02_00.40.27-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/6412154/crash-2021-05-02_00.40.27-client.txt)

If other blocks from the Secret Rooms mod are used we get small crashes (but the player can log back into the world):
[crash-2021-05-02_13.16.09-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/6412167/crash-2021-05-02_13.16.09-client.txt)

Please let me know if this can be patched.

**Comment by SuperMartijn642** [comment] 2021-05-08 13:04
I've now added a mod blacklist for allowed camouflage blocks in version 1.2.34. So blocks from the Secret Rooms Mod can no longer be used as camouflage.

Hopefully that should solves the issue.

**Comment by SuperMartijn642** [comment] 2021-05-16 14:01
I assume the issue is fixed now. If not, just comment here and I'll reopen the issue.

**Closed as completed by SuperMartijn642** 2021-05-16 14:01 UTC
Labels: crash

**Comment by MinicomSoftware** [comment] 2021-05-17 18:05
Oh, I forgot to respond. A few days after this patch I tested it and it did work. I also discovered another issue with the Secret Rooms mods. When you place a ghost block behind the elevator controller it crashes. I decided to not use the mods together.
