### ISSUE TITLE
[Crash] Camouflage crash

### ISSUE THREAD

**Issue by aruearoe** [SuperMartijn642/MovingElevators#221] opened 2024-06-03 22:43 UTC
Can someone who can solve this problem help me? Please.
⇒https://github.com/Fuzss/barteringstation/issues/11#issue-2331224989

**Version Info**
- Minecraft： ver.1.20.1
- Moving Elevators：movingelevators-1.4.7-fabric-mc1.20.1.jar

**Are you using OptiFine?**: Not used

**Steps to Reproduce**
Software does not start

**Crash report (https://github.com/user-attachments/files/15540480/latest.log)**
...

**Comment by SuperMartijn642** [comment] 2024-06-03 23:56
What are the steps to reproduce the issue? What were you doing when the crash occurred?

> Crash report (https://github.com/user-attachments/files/15540480/latest.log)

That log is pretty much just `Unknown custom packed identifier: appleskin:exhaustion_sync` spam 🤔
Looking at the logs in the issue you linked, it looks like some elevator block is camouflaged as itself somehow.

**Comment by SuperMartijn642** [comment] 2024-09-01 19:46
Closing this as I can't do anything without more info.

**Closed as completed by SuperMartijn642** 2024-09-01 19:46 UTC
Labels: crash
