### ISSUE TITLE
Fall Damage on Descent

### ISSUE THREAD

**Issue by UnseenAcademical** [SuperMartijn642/MovingElevators#17] opened 2020-04-23 20:54 UTC
When on an elevator configured with the default 0.2 blocks/tick, if going down, the player will take fall damage.

**Comment by SuperMartijn642** [comment] 2020-04-23 20:56
What Minecraft version and Moving Elevators version are you using?

**Comment by UnseenAcademical** [comment] 2020-04-24 00:33
1.14.4, Forge 28.2.3, movingelevators 1.2.8

**Comment by SuperMartijn642** [comment] 2020-04-24 07:18
This doesn't happen for me.
Does this always happen or just sometimes?
Are you playing on a server or singleplayer, and is there lag when it happens?
Are you using other mods?
Is there something, you think might be causing it?

**Comment by UnseenAcademical** [comment] 2020-04-24 14:46
Intermittently, server, no lag noticeable, plenty of other mods, can't immediately think of anything that would be causing it.

I tried to test today and was unable to replicate since the server reboot this morning. I'll keep an eye on it and see if I can find a common thread when it happens.

**Comment by SuperMartijn642** [comment] 2020-04-25 13:31
For now I will close the issue, if it starts to happen again feel free to reopen

**Comment by YuRaNnNzZZ** [comment] 2020-04-27 10:06
Same issue here. MC 1.12.2, mod version 1.2.11.
https://yurie.thigh-high.club/hm3nu7q5.mp4
Only have this issue on Sponge instance with a lot of mods and plugins running. Can't reproduce in singleplayer, local server with and without Sponge (with Sponge it also kicks for floating too long). It could be related to more server load i guess.

**Comment by SuperMartijn642** [comment] 2020-04-27 10:10
Oh seems like it's not resetting the fall distance and onGround flag, that's also why you normally get kicked for flying. It is weird that it only happens with Sponge servers though.

**Comment by YuRaNnNzZZ** [comment] 2020-04-27 10:58
> It is weird that it only happens with Sponge servers though.

Not just Sponge. I just tested on just Forge, it kicks for that as well.

**Comment by SuperMartijn642** [comment] 2020-04-27 11:03
Both with and without Sponge I don't get kicked on a local server when I test it.
Edit: Nevermind, I wasn't on the elevator for long enough.

**Comment by SuperMartijn642** [comment] 2020-04-27 12:06
I fixed the issue with getting kicked for floating.
I can't however replicate the issue with taking damage when the elevator arrives. I suspect this has something to do with one of the plugins or mods.

**Comment by YuRaNnNzZZ** [comment] 2020-04-27 13:03
I can reproduce that on Forge-only server by spawning a lot of villagers so that server starts lagging.
https://yurie.thigh-high.club/y63k05nv.mp4

**Comment by SuperMartijn642** [comment] 2020-04-30 09:53
I think I might have finally fixed it in version 1.2.14.

**Comment by WenXin20** [comment] 2020-05-01 00:23
In 1.2.14, I'm still dying to fall damage. I had it set to 0.4t or higher.
The damage only seems to occur if the player is moving when elevator stops.

**Comment by YuRaNnNzZZ** [comment] 2020-05-01 09:34
1.2.14, 0.2 blocks/t, fall damage even in singleplayer when server is lagging.
https://yurie.thigh-high.club/sig4jdjt.mp4

**Comment by SuperMartijn642** [comment] 2020-05-12 13:36
In version 1.2.14, I canceled all fall damage when on the platform and for 5 seconds after. I now changed it to be 100 ticks instead of 5 seconds.
I also cancel fall damage client side now, since it seems to happen client side before the elevator even arrives on the server. I had no clue fall damage was even handled client side.
I really hope this fixes it.

**Comment by YuRaNnNzZZ** [comment] 2020-05-25 13:29
I have no idea how it happens and why it happens. Different server, stable 20 TPS, pretty powerful hardware (which means it's not related to any slowdowns), no Sponge installed, 1.2.16 (latest version of the mod)
Yet still...
![javaw_2020-05-25_16-25-56](https://user-images.githubusercontent.com/5104603/82816973-c975ff00-9ea4-11ea-9832-44330df22cd0.png)
![](https://cdn.discordapp.com/attachments/519463352125227010/714469942086467584/unknown.png)

Edit: built a test elevator and did a few runs on it: https://yurie.thigh-high.club/51pfb2v6.mp4

**Comment by SilentChaos512** [comment] 2020-08-11 02:39
Getting this issue on 1.2.17a, MC 1.16.1. Multiplayer server, little to no lag. In my case, it seems to only happen when I use an Elevator Monitor to go from the surface (Y 64) to my base at Y 20. Going to the floor above at Y 30 doesn't cause any damage. Maybe just a coincidence, but might be worth checking.

**Comment by SuperMartijn642** [comment] 2020-08-11 05:04
I will be redoing the elevator collision and movement this week, so hopefully this issue gets fixed in the process.

**Comment by SuperMartijn642** [comment] 2020-08-13 16:42
I found the actual issue this time instead of just trying to randomly add extra measures.
It should (hopefully) be fixed now in version 1.2.18.

**Comment by SilentChaos512** [comment] 2020-08-18 22:17
Just had a chance to retest on version 1.2.20. Not having any issues. Thanks!

**Closed as completed** 2020-09-01 16:53 UTC
Labels: bug
