### ISSUE TITLE
[Crash] Game won't load

### ISSUE THREAD

**Issue by KrolMC** [SuperMartijn642/MovingElevators#65] opened 2021-07-26 06:29 UTC
Hello,
When added Moving Elevators mod game won't load with message: "Moving Elevators (movingelevators) has failed to load correctly java.langExceptionInInitializerError: null"
**Version Info**
- Minecraft: 1.17.1
- Moving Elevators: 1.2.34

**Crash report (~/logs/latest.log)**
[crash-2021-07-26_08.25.32-fml.txt](https://github.com/SuperMartijn642/MovingElevators/files/6876087/crash-2021-07-26_08.25.32-fml.txt)
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/6876090/latest.log)

**Comment by SuperMartijn642** [comment] 2021-07-26 12:35
Duplicate of #64

**Closed as completed by SuperMartijn642** 2021-07-26 12:35 UTC
Labels: duplicate, crash
