### ISSUE TITLE
[Crash] Crash when breaking a controller

### ISSUE THREAD

**Issue by SavageEagle001** [SuperMartijn642/MovingElevators#116] opened 2022-04-04 06:56 UTC
**Version Info**
- Minecraft, Version 1.18.1
- Moving Elevators, 1.3.3
**Are you using OptiFine?**: Yes

**Steps to Reproduce**
Crashes the game when breaking the controller block

**Crash report (~/logs/latest.log)**
...

**Comment by SuperMartijn642** [comment] 2022-04-04 11:55
Should already be fixed in Moving Elevators 1.3.6.

**Comment by SavageEagle001** [comment] 2022-04-04 17:55
With Minecraft version 1.18.1? it was crashing and the floor was like rotated sideways and invisible when I operated it lol

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SuperMartijn642** [comment] 2022-04-15 15:39
> With Minecraft version 1.18.1?

Yes... Like I said it, is already fixed in Moving Elevators 1.3.6.

> it was crashing and the floor was like rotated sideways and invisible when I operated it lol

This is already reported in #108. It is caused by OptiFine, nothing I can do about it. Just don't use OptiFine.

**Closed as completed by SuperMartijn642** 2022-04-15 15:39 UTC
Labels: crash
