### ISSUE TITLE
movingelevators-1.2.1-mc1.12 Bug and Improvements for the next Versions.

### ISSUE THREAD

**Issue by Titoo8899** [SuperMartijn642/MovingElevators#8] opened 2020-04-10 18:10 UTC
Hi, 
I love your mod and your Design but in the Mod give it a Problem with disguised of Blocks. I have testet and on the Screens can you show it work but the block texture is a little bit broken on your blocks. I hope you can fix this.
The other think is the new Elevator Display Block. The Idear is good but the Placement of the names of the Floor is not good. I hope you can fix this what you see in the screens and the Placement on the middle of the block make.

![2020-04-10_19 52 51](https://user-images.githubusercontent.com/42325138/79012679-23c23700-7b67-11ea-8f44-8a8732b74934.png)
![2020-04-10_19 54 16](https://user-images.githubusercontent.com/42325138/79012682-245acd80-7b67-11ea-98ac-1b01e0a57b91.png)
![2020-04-10_20 02 34](https://user-images.githubusercontent.com/42325138/79012685-24f36400-7b67-11ea-9b26-e28bfc330c1a.png)
![2020-04-10_20 02 40](https://user-images.githubusercontent.com/42325138/79012686-258bfa80-7b67-11ea-93ed-b9b22d35ee04.png)
![2020-04-10_20 03 13](https://user-images.githubusercontent.com/42325138/79012689-27ee5480-7b67-11ea-87d7-0a781db39713.png)

**Comment by SuperMartijn642** [comment] 2020-04-10 18:24
Can you test this with only Moving Elevators installed, because for me the block disguise renders just fine.
Could you also send a screenshot of your video settings, because it might be with a certain setting there?

As for the Elevator Display, the floor you are on is in the center of the display, and then it displays 3 floors up and 3 floors down. Thus that works as intended.

Edit: Another question, are you using Optifine?

**Comment by SuperMartijn642** [comment] 2020-04-10 18:25
Another question, are you using Optifine?

**Comment by Titoo8899** [comment] 2020-04-10 19:03
Hi, no I play only with this mods. Not Shaders or Optifine have I installed. And I will show then I only your mod install with the disguised of Blocks.

**Comment by SuperMartijn642** [comment] 2020-04-10 19:32
In your screenshots I can see a minimap and some overlay in the bottom right, thus indicating that you do have other mods installed.

**Comment by SuperMartijn642** [comment] 2020-04-10 20:47
Should be fixed now in version 1.2.2

**Closed as completed by SuperMartijn642** 2020-04-10 20:47 UTC
Labels: bug
