### ISSUE TITLE
[Crash] Minecraft 1.12.2

### ISSUE THREAD

**Issue by gri3229** [SuperMartijn642/MovingElevators#156] opened 2023-04-01 06:53 UTC
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-04-01 11:45:21 YEKT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1141)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_361, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 223398136 bytes (213 MB) / 547966976 bytes (522 MB) up to 8375238656 bytes (7987 MB)
  JVM Flags: 5 total; -Xmx8000M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G6_pre1 158 mods loaded, 158 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                             | Source                                                      | Signature                                |
       |:----- |:--------------------------------- |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft                         | 1.12.2                              | minecraft.jar                                               | None                                     |
       | L     | mcp                               | 9.42                                | minecraft.jar                                               | None                                     |
       | L     | FML                               | 8.0.99.99                           | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                             | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | advsolarpatch                     | 1.2.1                               | minecraft.jar                                               | None                                     |
       | L     | micdoodlecore                     | 4.0.4                               | minecraft.jar                                               | None                                     |
       | L     | smoothfontcore                    | mc1.12.2-2.1.4                      | minecraft.jar                                               | None                                     |
       | L     | openmodscore                      | 0.12.2                              | minecraft.jar                                               | None                                     |
       | L     | foamfixcore                       | 7.7.4                               | minecraft.jar                                               | None                                     |
       | L     | tickcentral                       | 3.2                                 | TickCentral-3.2.jar                                         | None                                     |
       | L     | concheckrmd                       | 1.9.5                               | Modpack+Configuration+Checker-1.12.2-v1.9.5.jar             | None                                     |
       | L     | smoothfont                        | mc1.12.2-2.1.4                      | SmoothFont-mc1.12.2-2.1.4.jar                               | None                                     |
       | L     | actuallyadditions                 | 1.12.2-r152                         | ActuallyAdditions-1.12.2-r152.jar                           | None                                     |
       | L     | ic2                               | 2.8.222-ex112                       | industrialcraft-2-2.8.222-ex112.jar                         | None                                     |
       | L     | redstoneflux                      | 2.1.1                               | RedstoneFlux-1.12-2.1.1.1-universal.jar                     | None                                     |
       | L     | cofhcore                          | 4.6.6                               | CoFHCore-1.12.2-4.6.6.1-universal.jar                       | None                                     |
       | L     | placebo                           | 1.6.0                               | Placebo-1.12.2-1.6.0.jar                                    | None                                     |
       | L     | thutcore                          | 5.21.0                              | thutcore-1.12.2-5.21.0.jar                                  | None                                     |
       | L     | thuttech                          | 6.1.6                               | thuttech-1.12.2-6.1.6.jar                                   | None                                     |
       | L     | industrialupgrade                 | 2.4.0.16                            | IndustrialUpgrade-1.12.2-2.4.0.16.jar                       | None                                     |
       | L     | powerutils                        | 1.3.1                               | Power+Utilities.jar                                         | None                                     |
       | L     | quantum_generators                | 1.2                                 | Quantum+Generators.jar                                      | None                                     |
       | L     | simplyquarries                    | 1.5                                 | Simply+Quarries.jar                                         | None                                     |
       | L     | advanced_solar_panels             | 4.3.0                               | Advanced+Solar+Panels-4.3.0.jar                             | None                                     |
       | L     | ctm                               | MC1.12.2-1.0.2.31                   | CTM-MC1.12.2-1.0.2.31.jar                                   | None                                     |
       | L     | appliedenergistics2               | rv6-stable-7-extended_life-v0.55.12 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.12.jar | None                                     |
       | L     | endercore                         | 1.12.2-0.5.76                       | EnderCore-1.12.2-0.5.76.jar                                 | None                                     |
       | L     | crafttweaker                      | 4.1.20                              | CraftTweaker2-1.12-4.1.20.687.jar                           | None                                     |
       | L     | jei                               | 4.16.1.1001                         | jei_1.12.2-4.16.1.1001.jar                                  | None                                     |
       | L     | codechickenlib                    | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | None                                     |
       | L     | brandonscore                      | 2.4.20                              | BrandonsCore-1.12.2-2.4.20.162-universal.jar                | None                                     |
       | L     | cofhworld                         | 1.4.0                               | CoFHWorld-1.12.2-1.4.0.1-universal.jar                      | None                                     |
       | L     | thermalfoundation                 | 2.6.7                               | ThermalFoundation-1.12.2-2.6.7.1-universal.jar              | None                                     |
       | L     | draconicevolution                 | 2.3.28                              | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar          | None                                     |
       | L     | thermalexpansion                  | 5.5.7                               | ThermalExpansion-1.12.2-5.5.7.1-universal.jar               | None                                     |
       | L     | enderio                           | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | p455w0rdslib                      | 2.3.161                             | p455w0rdslib-1.12.2-2.3.161.jar                             | None                                     |
       | L     | ae2wtlib                          | 1.0.34                              | AE2WTLib-1.12.2-1.0.34.jar                                  | None                                     |
       | L     | forgelin                          | 1.8.4                               | Forgelin-1.8.4.jar                                          | None                                     |
       | L     | waila                             | 1.8.26                              | Hwyla-1.8.26-B41_1.12.2.jar                                 | None                                     |
       | L     | aeadditions                       | 1.3.8                               | AEAdditions-1.12.2-1.3.8.jar                                | None                                     |
       | L     | backpacks16840                    | 3.5.12                              | backpacks+1.12.2+-+3.5.12.jar                               | None                                     |
       | L     | bdlib                             | 1.14.3.12                           | bdlib-1.14.3.12-mc1.12.2.jar                                | None                                     |
       | L     | betteradvancements                | 0.1.0.77                            | BetterAdvancements-1.12.2-0.1.0.77.jar                      | None                                     |
       | L     | bibliocraft                       | 2.4.6                               | BiblioCraft[v2.4.6][MC1.12.2].jar                           | None                                     |
       | L     | bookshelf                         | 2.3.589                             | Bookshelf-1.12.2-2.3.589.jar                                | None                                     |
       | L     | buildcraftlib                     | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftcore                    | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftbuilders                | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcrafttransport               | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftsilicon                 | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftcompat                  | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftenergy                  | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftfactory                 | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | buildcraftrobotics                | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
       | L     | chameleon                         | 1.12-4.1.3                          | Chameleon-1.12-4.1.3.jar                                    | None                                     |
       | L     | chickenchunks                     | 2.4.2.74                            | ChickenChunks-1.12.2-2.4.2.74-universal.jar                 | None                                     |
       | L     | chunkpregenerator                 | 2.5.0                               | Chunk+Pregenerator-V1.12-2.5.7.jar                          | None                                     |
       | L     | clickmachine                      | 1.2.0                               | ClickMachine-1.12.2-1.2.0.jar                               | None                                     |
       | L     | clumps                            | 3.1.2                               | Clumps-3.1.2.jar                                            | None                                     |
       | L     | ctgui                             | 1.0.0                               | CraftTweaker2-1.12-4.1.20.687.jar                           | None                                     |
       | L     | crafttweakerjei                   | 2.0.3                               | CraftTweaker2-1.12-4.1.20.687.jar                           | None                                     |
       | L     | cyclopscore                       | 1.6.7                               | CyclopsCore-1.12.2-1.6.7.jar                                | None                                     |
       | L     | durabilityshow                    | 5.0.0                               | Durability Show-1.12-5.0.0.jar                              | None                                     |
       | L     | eplus                             | 5.0.179                             | EnchantingPlus-1.12.2-5.0.179.jar                           | None                                     |
       | L     | endercompass                      | 1.2.6.2                             | EnderCompass-1.12-1.2.6.2.jar                               | None                                     |
       | L     | enderiointegrationtic             | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderiobase                       | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderioconduits                   | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderioconduitsappliedenergistics | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderioconduitsopencomputers      | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderioconduitsrefinedstorage     | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderiointegrationforestry        | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderiointegrationticlate         | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderioinvpanel                   | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderiomachines                   | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderiopowertools                 | 5.3.70                              | EnderIO-1.12.2-5.3.70.jar                                   | None                                     |
       | L     | enderstorage                      | 2.4.6.137                           | EnderStorage-1.12.2-2.4.6.137-universal.jar                 | None                                     |
       | L     | energycontrol                     | 1.12.2-0.3.1                        | EnergyControl-1.12.2-0.3.1.jar                              | None                                     |
       | L     | energyconverters                  | 1.3.7.30                            | energyconverters_1.12.2-1.3.7.30.jar                        | None                                     |
       | L     | engineersdecor                    | 1.1.3                               | engineersdecor-1.12.2-1.1.3.jar                             | None                                     |
       | L     | extracpus                         | 1.12.2-1.2.1                        | extracpus-1.12.2-1.2.1.jar                                  | None                                     |
       | L     | galacticraftcore                  | 4.0.4                               | Galacticraft-1.12.2-4.0.4.jar                               | None                                     |
       | L     | galacticraftplanets               | 4.0.4                               | Galacticraft-1.12.2-4.0.4.jar                               | None                                     |
       | L     | mjrlegendslib                     | 1.12.2-1.2.1                        | MJRLegendsLib-1.12.2-1.2.1.jar                              | None                                     |
       | L     | extraplanets                      | 1.12.2-0.7.4                        | ExtraPlanets-1.12.2-0.7.4.jar                               | None                                     |
       | L     | extrautils2                       | 1.0                                 | extrautils2-1.12-1.9.9.jar                                  | None                                     |
       | L     | findercompass                     | 1.12                                | FinderCompass-1.12.1.jar                                    | None                                     |
       | L     | ae2fc                             | 2.4.16-r                            | Fluid+Craft+for+AE2-2.4.16-r.jar                            | None                                     |
       | L     | sonarcore                         | 5.0.19                              | sonarcore-1.12.2-5.0.19-20.jar                              | None                                     |
       | L     | fluxnetworks                      | 4.1.0                               | FluxNetworks-1.12.2-4.1.1.34.jar                            | None                                     |
       | L     | foamfix                           | @VERSION@                           | foamfix-0.10.15-1.12.2.jar                                  | None                                     |
       | L     | forgemultipartcbe                 | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | L     | microblockcbe                     | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | L     | minecraftmultipartcbe             | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | L     | cfm                               | 6.3.0                               | furniture-6.3.2-1.12.2.jar                                  | None                                     |
       | L     | gravestone                        | 1.3.1                               | GraveStone-1.12.2-Graves-1.3.1.jar                          | None                                     |
       | L     | gravisuite                        | 3.1.1                               | Gravitation+Suite-3.1.1.jar                                 | None                                     |
       | L     | jaopcagtceu                       | 1.12.2-1.0.0.2                      | JAOPCAGTCEu-1.12.2-1.0.0.2.jar                              | None                                     |
       | L     | gregtech                          | 2.5.4                               | gregtech-1.12.2-2.5.4-beta.jar                              | None                                     |
       | L     | gcym                              | @VERSION@                           | GregicalityMultiblocks-1.12.2-1.2.0.jar                     | None                                     |
       | L     | gunpowderlib                      | 1.12.2-1.1                          | GunpowderLib-1.12.2-1.1.jar                                 | None                                     |
       | L     | hammercore                        | 2.0.6.32                            | HammerLib-1.12.2-2.0.6.32.jar                               | None                                     |
       | L     | twilightforest                    | 3.11.1021                           | twilightforest-1.12.2-3.11.1021-universal.jar               | None                                     |
       | L     | immersiveengineering              | 0.12-98                             | ImmersiveEngineering-0.12-98.jar                            | None                                     |
       | L     | immersivepetroleum                | 1.1.10                              | immersivepetroleum-1.12.2-1.1.10.jar                        | None                                     |
       | L     | trackapi                          | 1.2                                 | TrackAPI-1.2.jar                                            | None                                     |
       | L     | universalmodcore                  | 1.1.3                               | UniversalModCore-1.12.2-forge-1.1.3.jar                     | None                                     |
       | L     | immersiverailroading              | 1.9.1                               | ImmersiveRailroading-1.12.2-forge-1.9.1.jar                 | None                                     |
       | L     | teslacorelib                      | 1.0.18                              | tesla-core-lib-1.12.2-1.0.18.jar                            | None                                     |
       | L     | industrialforegoing               | 1.12.2-1.12.2                       | industrialforegoing-1.12.2-1.12.13-237.jar                  | None                                     |
       | L     | industrialrenewal                 | 0.21.8                              | IndustrialRenewal_1.12.2-0.21.8.jar                         | None                                     |
       | L     | nuclearcraft                      | 2.18zzz                             | NuclearCraft-2.18zzz-1.12.2.jar                             | None                                     |
       | L     | integrationforegoing              | 1.12.2-1.11                         | IntegrationForegoing-1.12.2-1.11.jar                        | None                                     |
       | L     | inventorytweaks                   | 1.64+dev.146.2180b27                | InventoryTweaks-1.64+dev.146.jar                            | None                                     |
       | L     | jaopca                            | 1.12.2-2.3.8.13                     | JAOPCA-1.12.2-2.3.8.13.jar                                  | None                                     |
       | L     | jeiintegration                    | 1.6.0                               | jeiintegration_1.12.2-1.6.0.jar                             | None                                     |
       | L     | journeymap                        | 1.12.2-5.7.1                        | journeymap-1.12.2-5.7.1.jar                                 | None                                     |
       | L     | justenoughbuttons                 | 1.12-1.2                            | justenoughbuttons-1.12.2-1.2.3.jar                          | None                                     |
       | L     | jeresources                       | 0.9.3.203                           | JustEnoughResources-1.12.2-0.9.3.203.jar                    | None                                     |
       | L     | laggoggles                        | 1.12.2-5.8-132                      | LagGoggles-1.12.2-5.8-132.jar                               | None                                     |
       | L     | libnine                           | 1.2.1                               | libnine-1.12.2-1.2.1.jar                                    | None                                     |
       | L     | threng                            | 1.1.26                              | lazy-ae2-1.12.2-1.1.26.jar                                  | None                                     |
       | L     | immersivetech                     | 1.9.100                             | MCTImmersiveTechnology-1.12.2-1.9.100.jar                   | None                                     |
       | L     | supermartijn642configlib          | 1.1.6                               | supermartijn642configlib-1.1.6-forge-mc1.12 (1).jar         | None                                     |
       | L     | supermartijn642corelib            | 1.1.6                               | supermartijn642corelib-1.1.6-forge-mc1.12 (1).jar           | None                                     |
       | L     | movingelevators                   | 1.3.12                              | movingelevators-1.3.12-forge-mc1.12.jar                     | None                                     |
       | L     | naturescompass                    | 1.8.5                               | NaturesCompass-1.12.2-1.8.5.jar                             | None                                     |
       | L     | reactorbuilder                    | 1.0.2                               | NC-ReactorBuilder-1.12.2-1.0.2.jar                          | None                                     |
       | L     | neenergistics                     | 2.0.3                               | NotEnoughEnergistics-1.12.2-2.0.3.jar                       | None                                     |
       | L     | openmods                          | 0.12.2                              | OpenModsLib-1.12.2-0.12.2.jar                               | None                                     |
       | L     | openblocks                        | 1.8.1                               | OpenBlocks-1.12.2-1.8.1.jar                                 | None                                     |
       | L     | oreexcavation                     | 1.4.150                             | OreExcavation-1.4.150.jar                                   | None                                     |
       | L     | prefab                            | 1.3.1.7                             | prefab-1.3.1.7.jar                                          | None                                     |
       | L     | projectintelligence               | 1.0.9                               | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar           | None                                     |
       | L     | scannable                         | 1.6.3.26                            | Scannable-MC1.12.2-1.6.3.26.jar                             | None                                     |
       | L     | solarflux                         | 12.4.11                             | SolarFluxReborn-1.12.2-12.4.11.jar                          | None                                     |
       | L     | storagedrawers                    | 5.2.2                               | StorageDrawers-1.12.2-5.4.2.jar                             | None                                     |
       | L     | surge                             | 2.0.79                              | Surge-1.12.2-2.0.79.jar                                     | None                                     |
       | L     | thermaldynamics                   | 2.5.6                               | ThermalDynamics-1.12.2-2.5.6.1-universal.jar                | None                                     |
       | L     | thermalinnovation                 | 0.3.6                               | ThermalInnovation-1.12.2-0.3.6.1-universal.jar              | None                                     |
       | L     | thutcore_compat                   | 1.0                                 | thutcore-1.12.2-5.21.0.jar                                  | None                                     |
       | L     | vanillafix                        | 1.0.10-150                          | VanillaFix-1.0.10-150.jar                                   | None                                     |
       | L     | wailaharvestability               | 1.1.12                              | WailaHarvestability-mc1.12-1.1.12.jar                       | None                                     |
       | L     | wanionlib                         | 1.12.2-2.9                          | WanionLib-1.12.2-2.9.jar                                    | None                                     |
       | L     | wawla                             | 2.6.275                             | Wawla-1.12.2-2.6.275.jar                                    | None                                     |
       | L     | wirelesstools                     | 1.1.20                              | wireless-industry-1.1.20-release.jar                        | None                                     |
       | L     | wct                               | 3.12.97                             | WirelessCraftingTerminal-1.12.2-3.12.97.jar                 | None                                     |
       | L     | wft                               | 1.0.4                               | WirelessFluidTerminal-1.12.2-1.0.4.jar                      | None                                     |
       | L     | wit                               | 1.0.2                               | WirelessInterfaceTerminal-1.12.2-1.0.2.jar                  | None                                     |
       | L     | wpt                               | 1.0.3                               | WirelessPatternTerminal-1.12.2-1.0.3.jar                    | None                                     |
       | L     | xray                              | 2.0.0                               | xray-1.12.2-1.6.0.jar                                       | None                                     |
       | L     | structurize                       | 1.12.2-0.10.277-RELEASE             | structurize-1.12.2-0.10.277-RELEASE.jar                     | None                                     |
       | L     | minecolonies                      | 1.12.2-0.11.841-ALPHA               | minecolonies-1.12.2-0.11.841-BETA-universal.jar             | None                                     |
       | L     | phosphor-lighting                 | 1.12.2-0.2.6                        | phosphor-1.12.2-0.2.6build50-universal.jar                  | None                                     |
       | L     | teslacorelib_registries           | 1.0.18                              | tesla-core-lib-1.12.2-1.0.18.jar                            | None                                     |
       | L     | unidict                           | 1.12.2-3.0.10                       | UniDict-1.12.2-3.0.10.jar                                   | None                                     |
       | L     | wrapup                            | 1.12-1.1.3                          | WrapUp-1.12-1.1.3.jar                                       | None                                     |
  Loaded coremods (and transformers): PatcherPlugin (AdvSolarPatch-1.2.1.jar)
                                        mods.su5ed.advsolarpatch.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      FluidCraftCore (Fluid+Craft+for+AE2-2.4.16-r.jar)
                                        com.glodblock.github.coremod.FCClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6build50-universal.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      BCModPlugin (backpacks+1.12.2+-+3.5.12.jar)
                                        brad16840.core.ClassTransformer
                                      SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.6-forge-mc1.12 (1).jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
                                        bre.smoothfont.asm.Transformer
                                      TickCentral (TickCentral-3.2.jar)
                                        com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer
                                        com.github.terminatornl.laggoggles.tickcentral.RenderManagerTransformer
                                        com.github.terminatornl.tickcentral.asm.BlockTransformer
                                        com.github.terminatornl.tickcentral.asm.ITickableTransformer
                                        com.github.terminatornl.tickcentral.asm.EntityTransformer
                                        com.github.terminatornl.tickcentral.asm.HubAPITransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      FCFMLCorePlugin (FinderCompass-1.12.1.jar)
                                        atomicstryker.findercompass.client.coremod.FCTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      MicdoodlePlugin (Galacticraft-1.12.2-4.0.4.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
                                        wanion.unidict.core.UniDictCoreModTransformer
                                      NEELoadingPlugin (NotEnoughEnergistics-1.12.2-2.0.3.jar)
                                        com.github.vfyjxf.nee.asm.NEEClassTransformer
                                      ECHookLoader (EnergyControl-1.12.2-0.3.1.jar)
                                        com.zuxelus.hooklib.minecraft.PrimaryClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.12.jar)
                                        appeng.core.transformer.AE2ELTransformer
                                      HCASM (HammerLib-1.12.2-2.0.6.32.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.5.4-beta.jar)
                                        gregtech.asm.GregTechTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.87' Renderer: 'GeForce GTX 750/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Русский (Россия)
  Profiler Position: N/A (disabled)
  CPU: 8x AMD FX(tm)-8300 Eight-Core Processor

**Comment by SuperMartijn642** [comment] 2023-04-01 11:28
Probably caused by Phosphor. Phosphor for Forge has been unsupported for years now and its source code is no longer available, so there's nothing I can do about it. Just don't use Phosphor.

If it is not Phosphor, please narrow the other mods needed to reproduce the issue and let me know.

**Comment by gri3229** [comment] 2023-04-01 13:16
> Probably caused by Phosphor. Phosphor for Forge has been unsupported for years now and its source code is no longer available, so there's nothing I can do about it. Just don't use Phosphor.
> 
> If it is not Phosphor, please narrow the other mods needed to reproduce the issue and let me know.

Removed the Phosphor mod from the assembly - nothing has changed. The crash details remain the same.

**Comment by SuperMartijn642** [comment] 2023-04-01 13:39
You're using a lot of other mods, please narrow down the mods needed to reproduce the issue.

**Comment by gri3229** [comment] 2023-04-01 15:57
> java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader


At random, I determined that the VanillaFix-1.0.10-150 mod became the cause of the crash. If there is an opportunity to somehow make friends with yours and this mod, I will be very grateful.

**Comment by SuperMartijn642** [comment] 2023-04-24 21:12
As this is unrelated to Moving Elevators itself, I will close the issue.

**Closed as completed by SuperMartijn642** 2023-04-24 21:12 UTC
Labels: crash
