### ISSUE TITLE
[Bug] Air replaced by waterlogged blocks

### ISSUE THREAD

**Issue by TheCardyMan** [SuperMartijn642/MovingElevators#230] opened 2024-08-19 21:51 UTC
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.7

**Are you using OptiFine?**: No

**Description of the Bug**
Using the More Decoration modpack, after moving an elevator, all of the air in it turns into waterlogged blocks. It was waterlogged iron ender chests from Wider Ender Chests, but I removed that mod and it was fixed, but then I added Sliding Doors and now it's waterlogged sliding doors.

**Steps to Reproduce**
1) Install the More Decorations modpack by Lupin
2) Add Sliding Doors by Alexander8VKHZ
3) Create an elevator
4) Move the elevator between floors

**Screenshots**
![image](https://github.com/user-attachments/assets/a81d0417-e4c7-4ca3-9415-86faf1c76e91)
![image](https://github.com/user-attachments/assets/b915b3b7-4675-41cc-babd-654818c7e8e6)

**Comment by carloanselmini** [comment] 2024-09-01 17:23
Same on 1.21 and wider enderchest mod

**Comment by SuperMartijn642** [comment] 2024-09-01 19:40
@carloanselmini what modloader are you using?

**Comment by SuperMartijn642** [comment] 2024-09-02 14:48
This seems to have been caused by Wider Ender Chests registering their blocks in a non-ideal way, causing the vanilla block ids to be shifted to after Wider Ender Chests blocks. This meant the block at id 0 became a block from Wider Ender Chests rather then the vanilla air block.
This should now be fixed in Moving Elevators version 1.0.8 and I have also reported the issue to Wider Ender Chests.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-09-02 14:48 UTC
Labels: bug
