### ISSUE TITLE
[Bug] Buggy textures.

### ISSUE THREAD

**Issue by Gallardo7761** [SuperMartijn642/MovingElevators#136] opened 2022-07-14 06:43 UTC
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, 1.3.8

**Are you using OptiFine?**: I'm using optifine

**Description of the Bug**
The elevators look like in vertical floating next to me instead of its normal position with shaders installed.

**Steps to Reproduce**
...

**Screenshots**
![image](https://user-images.githubusercontent.com/100301878/178918221-32284071-79a6-444f-b279-4ed747b59754.png)

**Comment by SuperMartijn642** [comment] 2022-07-14 10:07
This might be a duplicate of #108, but you'd have to confirm.
Anyways, there's not much I can do about this as OptiFine is closed source, thus I can't know what it changes.

I can only recommend not using OptiFine. There are other open-source and community friendly alternatives for shaders such as [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus). I would suggest using those instead of OptiFine.

**Closed as completed** 2023-04-25 19:58 UTC
Labels: bug, Caused by OptiFine
